# Generated by Django 4.0.4 on 2022-05-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('website_link', models.CharField(max_length=100)),
                ('com_name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Rl_id', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
