# Generated by Django 4.0.4 on 2022-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_explore_delete_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='nt',
            field=models.CharField(default=234, max_length=400),
            preserve_default=False,
        ),
    ]
