# Generated by Django 4.0.4 on 2022-05-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_explore_nt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='salary',
        ),
    ]
